version: "3"

services:
  node:
    container_name: green-node
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 8080:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 10
        npm start
    restart: unless-stopped
    stdin_open: true
    tty: true
  db:
    image: mariadb
    ports:
      - 3307:3306
    env_file: .env
    volumes:
      - ./db/config/conf.d:/etc/mysql/conf.d
      - ./db/config/data:/var/lib/mysql
      - ./db/config/sql/:/docker-entrypoint-initdb.d/
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_PW
      - MARIADB_DATABASE=$DB_NAME
      - MARIADB_USER=$DB_USER
      - MARIADB_PASSWORD=$DB_PW
    networks:
      - backend
    restart: always
    container_name: green-db

networks:
  backend:
